### ISSUE TITLE
July 19th 2022 Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/curref-data#33]
# Currency Reference Data Meeting
[Currency Reference data overview, roadmap and background](https://github.com/finos/secref-data#currency-reference-data)

## Date
July 19th 2022 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Updated model @ElaineFraser @Vijayesh-Chandel 
- [ ] Duplicate minor units(?)
- [ ] Offshore currencies 
- [ ] Suggest future additions to the model to be discussed at future meetings.
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Share model @ElaineFraser @Vijayesh-Chandel 
- [ ] Reach out to CDM + other relevant groups @TheJuanAndOnly99 
- [ ] Move August meeting @TheJuanAndOnly99 

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by ElaineFraser** [comment]
hi

**Comment by ElaineFraser** [comment]
Service to show current draft data for minor units: https://legend.finos.org/studio/view/UAT-28796423/entity/Model::physicalModel::minorUnitService
Diagram: https://legend.finos.org/studio/view/UAT-28796423/entity/Model::ModelDiagram
Group workspace: https://legend.finos.org/studio/edit/UAT-28796423/groupWorkspace/MinorUnit/
